name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # تأكد من استخدام إصدار حديث من Node.js و npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20' # أو أي إصدار تدعمه
          cache: 'npm'

      # تثبيت الاعتماديات باستخدام npm ci
      - run: npm ci
      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMART_EFIS_GLOBAL }}
          channelId: live
          projectId: smart-efis-global
